Python: build --with-system-ffi.
This should solve the problem where the build uses include files from
vanilla libffi, but links against system (Apple) libffi, which causes
missing symbols at runtime:

$ jhbuild run 'python3 -m objc'
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/Users/catalinp/gtk/inst/lib/python3.11/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/Users/catalinp/gtk/inst/lib/python3.11/site-packages/objc/_objc.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_find_closure_for_code_np'

https://github.com/Xpra-org/gtk-osx-build/issues/27#issuecomment-1890480763